name: "simple github actions workflow"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "running date command"
        run: date
        shell: bash

      - name: "Getting os details"
        run: cat /etc/os-release
        shell: bash

      - name: "user details"
        run: whoami
        shell: bash

      - name: "Current working directory details before checkout"
        run: |
          pwd
          ls -al

      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Current working directory details after checkout"
        run: |
          pwd
          ls -al

      - name: "Installation of  Terraform(method2)"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.6"

      - name: "Terraform version"
        run: terraform version


      - name: "Running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh
